In [1]:
##1. NumPy Package
#1)ndarray vs list
import numpy as np
my_arr = np.arange(8)
my_list = list(range(8))
print(my_arr)
print(my_list)

[0 1 2 3 4 5 6 7]
[0, 1, 2, 3, 4, 5, 6, 7]


In [2]:
#2)Create NumPy Array
# Create a 3x3 array of all zeros 
a = np.zeros((3,3)) 
print (a)

# Create a 3x3 constant array
c = np.full((3,3), 7)
print (c)

# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print (d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.14292607 0.1934365  0.34104968]
 [0.11507612 0.28031704 0.90673372]
 [0.43371734 0.05413017 0.08223299]]


In [2]:
#3)Arithmaticwith NumPy Arrays
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr **2)
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
print(arr2 > arr)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
[[False  True False]
 [ True False  True]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#4)Indexing and Slicing
arr = np.arange(10)
print(arr)            # [0 1 2 3 4 5 6 7 8 9]
print(arr[5])         #5
arr_slice = arr[5:8]
print(arr_slice)      # [5 6 7]
arr_slice[1] = 12345
print(arr)             # [ 0 1 2 3 4 5 12345 7 8 9]
arr_slice[:] = 64
print(arr)             # [ 0 1 2 3 4 64 64 64 8 9]


[0 1 2 3 4 5 6 7 8 9]
9
[0 1 2 3 4 5 6 7 8]
5
[5 6 7]
[    0     1     2     3     4     5 12345     7     8     9]
[ 0  1  2  3  4 64 64 64  8  9]


In [7]:
# 5)Indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])             # [7 8 9]
print(arr2d[0][2])           # 3
print(arr2d[0, 2])           #3

[7 8 9]
3
3


In [10]:
import numpy as np 
data = [1,2,3,4,5]
mean = np.mean(data)
mean

arr = np.arange(5)
mean1 = np.mean(arr)
mean1

2.0

In [7]:
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
def square(x):
    return x * x
df1 = df.apply(square)
print(df)
print(df1)

   A   B
0  1  10
1  2  20
   A    B
0  1  100
1  4  400
